name: font_quiz
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2
  flutter_screenutil: ^5.0.1+2
  flutter_slider_drawer: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  freezed_annotation: ^1.1.0
  go_router: ^3.0.1
  google_fonts: 2.2.0
  hooks_riverpod: ^1.0.3
  intl: ^0.17.0
  json_annotation: ^4.4.0
  # mocktail: ^0.3.0
  path: ^1.8.0
  pedantic_mono: ^1.15.0
  provider: ^6.0.2
  sqflite: ^2.0.2
  sqlite_viewer: ^1.0.5
  audioplayers: ^0.20.1

dev_dependencies:
  build_runner: ^2.1.7
  flutter_gen_runner: ^4.1.5
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/image_false.jpeg
    - assets/images/image_true.jpeg
    - assets/json/settings.json
    - assets/correct.mp3
    - assets/incorrect.mp3
    - assets/switch.mp3
    
flutter_gen:
  output: lib/gen/
  lineLength: 80 
