# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on:
  workflow_dispatch:
    inputs:
      flutter-version:
        required: true
        type: string
  workflow_call:
    inputs:
      flutter-version:
        required: true
        type: string      

jobs:
  flutter-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 100

      - name: Setup flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: Get flutter packages
        run: flutter pub get

      - name: Run unit test
        run: flutter test --coverage --coverage-path=./coverage/lcov.info --machine > flutter_test_report.txt

      - name: Report test result
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: 'flutter test'
          path: 'flutter_test_report.txt'
          reporter: 'flutter-json'
          fail-on-error: 'false'

      - name: Upload a coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info

      # - name: Add problem matcher
      #   run: echo "::add-matcher::.github/analyzer-problem-matcher.json"
  
      - name: Check lint
        run: flutter analyze > flutter_analyze_report.txt || true

      - name: Check code metrics
        run: |
          flutter pub run dart_code_metrics:metrics analyze lib --reporter=console > dart-code-metrics_analyze_report.txt || true

      - name: Get changed files
        if: always()
        uses: ./.github/actions/get-chaged-files
        id: changed-files

      # - name: Annotation for lint checker
      #   if: always()
      #   run: |
      #     echo $CHANGED_FILES
      #     for FILE in $CHANGED_FILES; do
      #       echo "$FILE"
      #       grep -1 -E ".*$FILE.*" $LOG_FILE_PATH || [[ $? == 1 ]]
      #     done
      #   env:
      #     CHANGED_FILES: ${{ steps.changed-files.outputs.changed-files }}
      #     LOG_FILE_PATH: ./flutter_analyze_report.txt

      - name: Annotation for lint checker
        if: always()
        uses: ./.github/actions/annotate-problems
        with:
          matcher-config-path: .github/analyzer-problem-matcher.json
          analysis-report-path: ./flutter_analyze_report.txt
          changed-files: ${{ steps.changed-files.outputs.changed-files }}

      # - name: Annotation for DMC checker
      #   if: always()
      #   run: |
      #     echo $CHANGED_FILES
      #     for FILE in $CHANGED_FILES; do
      #       echo "$FILE"
      #       grep -1 -E ".*$FILE.*" $LOG_FILE_PATH || [[ $? == 1 ]]
      #     done
      #   env:
      #     CHANGED_FILES: ${{ steps.changed-files.outputs.changed-files }}
      #     LOG_FILE_PATH: ./dart-code-metrics_analyze_report.txt

      # - name: Remove problem matcher
      #   if: always()
      #   run: echo "::remove-matcher owner=dart-analyzer::"

      # - name: Setup Ruby
      #   uses: ruby/setup-ruby@v1
      #   if: always()
      #   with:
      #     ruby-version: '2.7'

      # - name: Install bundler
      #   run: gem install bundler

      # - name: Create pull-req omment 
      #   uses: MeilCli/danger-action@v5
      #   if: always()
      #   with:
      #     plugins_file: '.github/Gemfile'
      #     install_path: 'vendor/bundle'
      #     danger_file: '.github/Dangerfile'
      #     danger_id: 'danger-pr'
      #   env:
      #     DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
