# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Setup repository'
        uses: actions/checkout@v2

      - name: 'Setup java environment'
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: 'Setup flutter environment'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1'
          channel: 'stable'
          cache: true

      - name: 'Cache pubspec dependencies'
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.FLUTTER_HOME }}/.pub-cache
            **/.packages
            **/.flutter-plugins
            **/.flutter-plugin-dependencies
            **/.dart_tool/package_config.json
          key: build-pubspec-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            build-pubspec-

      - name: 'Run lint'
        run: flutter analyze

      - name: 'Run test'
        run: flutter test

      - name: 'Run Code Metrics'
        run: flutter pub run

      # — name: 'Run Code Metrics'
      #   run: flutter pub run dart_code_metrics:metrics analyze lib --reporter=github