# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on:
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repository
        uses: actions/checkout@v2

      - name: Setup flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1'
          channel: 'stable'
          cache: true

      - name: Cache pubspec dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.FLUTTER_HOME }}/.pub-cache
            **/.packages
            **/.flutter-plugins
            **/.flutter-plugin-dependencies
            **/.dart_tool/package_config.json
          key: build-pubspec-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            build-pubspec-

      - name: Get Flutter Packages
        run: flutter pub get

      - name: Add problem matcher
        run: echo "::add-matcher::.github/analyzer-problem-matcher.json"

      - name: Run lint
        run: flutter analyze | tee ./flutter_analyze_report.txt

      - name: Run test
        run: flutter test --coverage --coverage-path=./coverage/lcov.info

      - name: Run Code Metrics
        run: flutter pub run dart_code_metrics:metrics analyze lib --reporter=github

      - name: Upload a coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:  
          files: ./coverage/lcov.info

      - name: Remove problem matcher
        if: always()
        run: echo "::remove-matcher owner=dart-analyzer::"
